### ISSUE TITLE
Code review of deserialization

### ISSUE THREAD

**Issue by sjeon87** [proj3rd/lib3rd#144]
Commits
- bdf350a7c141cdf13334b2eed2ee303e1cba99ad
- 939fdb309f3da3b7c80258999dc993222c0e3757
- 8559a909b9febf87f016023e7631fe93960763c9
- f7cf58796d96de2d820c5c32fd1009f898fbf88c

Diff
https://github.com/proj3rd/lib3rd/compare/fb669f3ad0ac7ac303ebfbbee73897dbaf3399b3..f7cf58796d96de2d820c5c32fd1009f898fbf88c

Files
- [x] src/asn1/classes/asnSymbol.ts
- [x] src/asn1/classes/asnType.ts
- [x] src/asn1/classes/atNotation.ts
- [x] src/asn1/classes/bitStringType.ts
- [x] src/asn1/classes/booleanType.ts
- [x] src/asn1/classes/booleanValue.ts
- [x] src/asn1/classes/characterStringType.ts
- [x] src/asn1/classes/choiceType.ts
- [x] src/asn1/classes/componentPresence.ts
- [x] src/asn1/classes/componentRelationConstraint.ts
- [x] src/asn1/classes/componentType.ts
- [x] src/asn1/classes/constraint.ts
- [x] src/asn1/classes/contentsConstraint.ts
- [x] src/asn1/classes/definitiveIdentification.ts
- [x] src/asn1/classes/enumeratedType.ts
- [x] src/asn1/classes/extensionAdditionAlternativeGroup.ts
- [x] src/asn1/classes/extensionAdditionGroup.ts
- [x] src/asn1/classes/extensionMarker.ts
- [x] src/asn1/classes/externalObjectSetReference.ts
- [x] src/asn1/classes/externalTypeReference.ts
- [x] src/asn1/classes/fixedTypeValueFieldSpec.ts
- [x] src/asn1/classes/imports.ts
- [x] src/asn1/classes/innerTypeConstraints.ts
- [x] src/asn1/classes/integerType.ts
- [x] src/asn1/classes/integerValue.ts
- [x] src/asn1/classes/moduleDefinition.ts
- [x] src/asn1/classes/modules.ts
- [x] src/asn1/classes/namedType.ts
- [x] src/asn1/classes/nullType.ts
- [x] src/asn1/classes/objectClass.ts
- [x] src/asn1/classes/objectClassAssignment.ts
- [x] src/asn1/classes/objectClassFieldType.ts
- [x] src/asn1/classes/objectClassReference.ts
- [x] src/asn1/classes/objectIdentifierType.ts
- [x] src/asn1/classes/objectIdentifierValue.ts
- [x] src/asn1/classes/objectSet.ts
- [x] src/asn1/classes/objectSetAssignment.ts
- [x] src/asn1/classes/objectSetReference.ts
- [x] src/asn1/classes/octetStringType.ts
- [x] src/asn1/classes/optionality.ts
- [x] src/asn1/classes/parameter.ts
- [x] src/asn1/classes/parameterizedType.ts
- [x] src/asn1/classes/parameterizedTypeAssignment.ts
- [x] src/asn1/classes/primitiveFieldName.ts
- [x] src/asn1/classes/sequenceOfType.ts
- [x] src/asn1/classes/sequenceType.ts
- [x] src/asn1/classes/sizeConstraint.ts
- [x] src/asn1/classes/subtypeConstraint.ts
- [x] src/asn1/classes/symbolsFromModule.ts
- [x] src/asn1/classes/syntax.ts
- [x] src/asn1/classes/typeAssignment.ts
- [x] src/asn1/classes/typeFieldSpec.ts
- [x] src/asn1/classes/typeReference.ts
- [x] src/asn1/classes/unions.ts
- [x] src/asn1/classes/value.ts
- [x] src/asn1/classes/valueAssignment.ts
- [x] src/asn1/classes/valueRange.ts
- [x] src/asn1/classes/valueReference.ts
- [x] src/asn1/constants.ts
- [x] src/asn1/diff.ts
- [x] src/asn1/expander.ts
- [x] src/asn1/index.ts
- [x] src/asn1/types.ts
- [x] src/asn1/types/actualParamter.ts
- [x] src/asn1/types/asnType.ts
- [x] src/asn1/types/assignment.ts
- [x] src/asn1/types/constraintSpec.ts
- [x] src/asn1/types/definedObjectSet.ts
- [x] src/asn1/types/definitiveObjIdComponent.ts
- [x] src/asn1/types/elementSetSpec.ts
- [x] src/asn1/types/elementSetSpecs.ts
- [x] src/asn1/types/elements.ts
- [x] src/asn1/types/enumerationItem.ts
- [x] src/asn1/types/exports.ts
- [x] src/asn1/types/extensionDefault.ts
- [x] src/asn1/types/fieldSpec.ts
- [x] src/asn1/types/generalConstraint.ts
- [x] src/asn1/types/governor.ts
- [x] src/asn1/types/intersectionElements.ts
- [x] src/asn1/types/intersections.ts
- [x] src/asn1/types/namedBit.ts
- [x] src/asn1/types/namedNumber.ts
- [x] src/asn1/types/objectSetElements.ts
- [x] src/asn1/types/paramGovernor.ts
- [x] src/asn1/types/rootChoiceComponents.ts
- [x] src/asn1/types/rootSequenceComponents.ts
- [x] src/asn1/types/singleValue.ts
- [x] src/asn1/types/subtypeElements.ts
- [x] src/asn1/types/tableConstraint.ts
- [x] src/asn1/types/tagDefault.ts
- [x] src/asn1/types/typeConstraint.ts
- [x] src/asn1/types/typeConstraintsComponent.ts
- [x] src/asn1/types/value.ts
- [x] src/ran3/classes/definitions.ts
- [x] src/ran3/index.ts

**Comment by gsongsong** [comment]
939fdb309f3da3b7c80258999dc993222c0e3757

src/asn1/classes

- [ ] /bitStringType.ts
- [ ] src/asn1/classes/extensionAdditionAlternativeGroup.ts
- [ ] src/asn1/classes/parameter.ts
- [ ] src/asn1/classes/parameterizedTypeAssignment.ts
- [ ] src/asn1/classes/sequenceType.ts
- [ ] src/asn1/types.ts
- [ ] src/asn1/types/asnType.ts
- [ ] src/asn1/types/assignment.ts
- [ ] src/asn1/types/governor.ts
- [ ] src/asn1/types/paramGovernor


.ts
