### ISSUE TITLE
Parsing/Formatting RAN3 ASN.1

### ISSUE THREAD

**Issue by sjeon87** [proj3rd/lib3rd#57]
**IEs to be Tested**

- [ ] `HandoverRequiredIEs` (36.413)
- [ ] `SecondaryRATDataUsageReportList` (36.413)
- [ ] `SecondaryRATDataUsageRerpotIEs` (36.413)

**Comment by sjeon87** [comment]
`HandoverRequiredIEs`

![HandoverRequiredIEs 36413-g00](https://user-images.githubusercontent.com/6747391/76164093-5e633900-618f-11ea-90c9-f89673e5dee9.png)

`SecondaryRATDataUsageRerportIEs`

![SecondaryRATDataUsageRerpotIEs 36413-g00](https://user-images.githubusercontent.com/6747391/76420362-5997c280-63e5-11ea-9cf1-580d595d4ce3.png)

**Comment by sjeon87** [comment]
# `SecondaryRATDataUsageReportList`

```
SecondaryRATDataUsageReportList ::= SEQUENCE (SIZE(1.. maxnoofE-RABs)) OF ProtocolIE-SingleContainer { {SecondaryRATDataUsageReportItemIEs} }
```

![image](https://user-images.githubusercontent.com/6747391/79037419-ad2b4500-7c0b-11ea-9097-3bce77268d9a.png)

`ProtocolIE-SingleContainer`

![image](https://user-images.githubusercontent.com/6747391/79037409-94bb2a80-7c0b-11ea-92e8-8c4e29c06bcb.png)

```
Expanding... {
  "name": "SecondaryRATDataUsageReportList",
  "definition": {
    "type": {
      "typeReference": "ProtocolIE-SingleContainer",
      "actualParameterList": [
        {
          "objIdComponentsList": [
            "SecondaryRATDataUsageReportItemIEs"
          ]
        }
      ],
      "constraints": []
    },
    "constraints": [
      {
        "sizeConstraint": {
          "min": 1,
          "max": "maxnoofE-RABs"
        }
      }
    ],
    "moduleName": "S1AP-IEs"
  }
}
Expaned type: {
  "typeReference": "ProtocolIE-Field",
  "actualParameterList": [
    {
      "objIdComponentsList": [
        "IEsSetParam"
      ]
    }
  ],
  "constraints": [],
  "parameterList": [
    {
      "paramGovernor": {
        "typeReference": "S1AP-PROTOCOL-IES",
        "constraints": []
      },
      "dummyReference": "IEsSetParam"
    }
  ],
  "moduleName": "S1AP-Containers"
}
```

- [ ] `definedType.ts`: Compare `actualParameterist` of source and expanded IEs which exist in `parameterList`

**Comment by gsongsong** [comment]
`ProtocolIE-SingleContainer`

![ProtocolIE-SingleContainer](https://user-images.githubusercontent.com/6747391/76699974-f021f780-66f5-11ea-8fe9-70734670144b.png)

**Comment by gsongsong** [comment]
```
Expanding... {
  "name": "SecondaryRATDataUsageReportList",
  "definition": {
    "type": {
      "typeReference": "ProtocolIE-SingleContainer",
      "actualParameterList": [
        {
          "objIdComponentsList": [
            "SecondaryRATDataUsageReportItemIEs"
          ]
        }
      ],
      "constraints": []
    },
    "constraints": [
      {
        "sizeConstraint": {
          "min": 1,
          "max": "maxnoofE-RABs"
        }
      }
    ],
    "moduleName": "S1AP-IEs"
  }
}
Expaned type: {
  "typeReference": "ProtocolIE-Field",
  "actualParameterList": [
    {
      "objIdComponentsList": [
        "IEsSetParam"
      ]
    }
  ],
  "constraints": [],
  "parameterList": [
    {
      "paramGovernor": {
        "typeReference": "S1AP-PROTOCOL-IES",
        "constraints": []
      },
      "dummyReference": "IEsSetParam"
    }
  ],
  "moduleName": "S1AP-Containers"
}
```

**Comment by sjeon87** [comment]
# `SecondaryRATDataUsageReportItemIEs`

![SecondaryRATDataUsageReportItemIEs](https://user-images.githubusercontent.com/6747391/79062675-43786d00-7cd7-11ea-8077-eb327d80895b.png)

**Comment by sjeon87** [comment]
`expandedType` of `SequenceOf` class shall be able to contain multiple items, i.e. each element of `ObjectSet` or `ObjectSetSpec`

https://github.com/gsongsong/3gpp/blob/9c644da52273da1c7931b54636f6ec600a42b536/src/asn1/classes/sequenceOf.ts#L14-L19

**Comment by sjeon87** [comment]
~~Seems `Sequence.replaceParameters()` shall return `Sequence[]` if `Object Set` shall be expanded.~~

**Comment by sjeon87** [comment]
It would be good:

```ASN.1
{ -- ObjectSet
  SEQUENCE { ... } |
  SEQUENCE { ... } |
  SEQUENCE { ... },
  ...
}
```

**Comment by sjeon87** [comment]
- [ ] Need to test with https://github.com/gsongsong/grammars-v4/issues/7#issue-591973025

**Comment by sjeon87** [comment]
https://github.com/gsongsong/3gpp/issues/93

**Comment by sjeon87** [comment]
Working prototype done at e1de92024bf9d624ea2721dcd371a5e114eb6cc1

- [ ] Need to implement formating in xlsx

**Comment by sjeon87** [comment]
2ce9ac666047424f0693a312b3644d31ce1c30b1
